from os import environ

GEOIP_GEOLITE2_PATH = environ.get("GEOIP_GEOLITE2_PATH")
GEOIP_GEOLITE2_CITY_FILENAME = environ.get(
    "GEOIP_GEOLITE2_CITY_FILENAME", "GeoLite2-City.mmdb"
)

GEOIP_GEOLITE2_CITY_PATH = None
if GEOIP_GEOLITE2_PATH:
    GEOIP_GEOLITE2_CITY_PATH = GEOIP_GEOLITE2_PATH + GEOIP_GEOLITE2_CITY_FILENAME
